spring:
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: Root@30081997@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
